# online-reader-demo/ci-config.yml

language: python
has_api: true

# 开关控制
enable_lint: true          # 先不卡 Lint，跑通流程为主
enable_unit_test: true      # 开启核心测试
enable_contract_test: true  # 暂时关闭 API 合同测试
openapi_path: api-specs/openapi.yaml 
enable_build: false         # 暂时不构建产物
enable_coverage: false      # 暂时不看覆盖率
enable_docker_build: false  # 暂时不构建 Docker 镜像